In [1]:
import sys
sys.path.append("../modules")
from eda import EDAAnalyzer
from spark_session import SparkManager
from feature_engineering import FeatureEngineer

In [2]:
# Load autoreload extension
%load_ext autoreload
%autoreload 2

In [3]:
mx_submits_path = "../data_sample/mx_submits.parquet/"
mx_submits_line_path = "../data_sample/mx_submitsline.parquet/"

sample_patient_id = "8aad41f612a7095449888c8050abaeb05fdee65643caa3033542610421d8bd1daaa2c4ce1757401003a1bbcd60948a7aa13eba507a676dea80e0cf76b77dbc95"

In [4]:
mx_submits_spark_manager = SparkManager(mx_submits_path)

24/09/27 09:42:27 WARN Utils: Your hostname, Chaopings-MacBook-Air.local resolves to a loopback address: 127.0.0.1; using 10.0.0.231 instead (on interface en0)
24/09/27 09:42:27 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
24/09/27 09:42:27 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [5]:
mx_submits_line_spark_manager = SparkManager(mx_submits_line_path)

### Feature Engineer

In [6]:
mx_submits_line_fe = FeatureEngineer(mx_submits_line_spark_manager)

In [7]:
mx_submits_line_fe.add_procedure_array("principal_procedure_code", "claim_statement_from_date");

Initial DataFrame for principal_procedure_code - Shape: 15501334 rows, 150 columns
DataFrame After Window Function for principal_procedure_code - Shape: 15501334 rows, 153 columns

mx_submits_line_fe.add_procedure_array("line_level_procedure_code", "claim_statement_from_date");

In [8]:
sample_patient_info = mx_submits_line_fe.get_rows_by_column_value("patient_id",sample_patient_id)
sample_patient_info

24/09/27 09:42:38 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

,attending_provider_npi,billing_provider_address_cbsa_name,billing_provider_address_city,billing_provider_address_county,billing_provider_address_key,billing_provider_address_latitude,billing_provider_address_longitude,billing_provider_address_precision,billing_provider_address_region,billing_provider_address_state,...,line_level_procedure_modifier_4,line_level_procedure_category,line_level_revenue_code,line_level_revenue_description,line_level_from_date,line_level_to_date,line_level_units_billed,filtered_procedure,filtered_date,procedure_date_map
0,None,None,None,None,None,None,None,None,None,None,...,None,EVALUATION AND MANAGEMENT - OFFICE/OTHER OUTPA...,None,None,2015-02-03,2015-02-03,1.00,99213,2015-02-03,{}
1,None,"EVANSVILLE, IN-KY",Evansville,Vanderburgh,801SAINTMARYSDREVANSVILLEIN47714,37.965828,-87.504639,Street,Midwest,IN,...,None,EVALUATION AND MANAGEMENT - OFFICE/OTHER OUTPA...,None,None,2015-02-03,2015-02-03,1.00,99213,2015-02-03,{'99213': 2015-02-03}
2,None,None,None,None,None,None,None,None,None,None,...,None,EVALUATION AND MANAGEMENT - OFFICE/OTHER OUTPA...,None,None,2015-04-21,2015-04-21,1.00,99214,2015-04-21,{'99213': 2015-02-03}
3,None,"EVANSVILLE, IN-KY",Evansville,Vanderburgh,801SAINTMARYSDREVANSVILLEIN47714,37.965828,-87.504639,Street,Midwest,IN,...,None,EVALUATION AND MANAGEMENT - OFFICE/OTHER OUTPA...,None,None,2015-04-21,2015-04-21,1.00,99214,2015-04-21,"{'99214': 2015-04-21, '99213': 2015-02-03}"
4,None,"EVANSVILLE, IN-KY",Evansville,Vanderburgh,600MARYSTEVANSVILLEIN47710,37.983086,-87.570702,Street,Midwest,IN,...,None,None,None,None,2015-04-21,2015-04-21,1.00,36415,2015-04-21,"{'99214': 2015-04-21, '99213': 2015-02-03}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3979,1376869032,None,None,None,None,None,None,None,None,None,...,None,None,0301,Laboratory,2024-07-27,2024-07-27,1.00,81003,2024-07-27,"{'20610': 2022-06-27, '90686': 2016-11-15, '99..."
3980,1376869032,None,None,None,None,None,None,None,None,None,...,None,PATHOLOGY AND LABORATORY - ORGAN OR DISEASE-OR...,0300,Laboratory,2024-07-27,2024-07-27,1.00,81003,2024-07-27,"{'20610': 2022-06-27, '90686': 2016-11-15, '99..."
3981,1376869032,None,None,None,None,None,None,None,None,None,...,None,None,0636,Pharmacy,2024-07-27,2024-07-27,200.00,81003,2024-07-27,"{'20610': 2022-06-27, '90686': 2016-11-15, '99..."
3982,1376869032,None,None,None,None,None,None,None,None,None,...,None,None,0305,Laboratory,2024-07-27,2024-07-27,1.00,81003,2024-07-27,"{'20610': 2022-06-27, '90686': 2016-11-15, '99..."
3983,1376869032,None,None,None,None,None,None,None,None,None,...,None,"MEDICINE - HYDRATION, THERAPEUTIC, PROPHYLACTI...",0260,IV Therapy,2024-07-27,2024-07-27,1.00,81003,2024-07-27,"{'20610': 2022-06-27, '90686': 2016-11-15, '99..."

In [9]:
sample_patient_info[["patient_id","claim_statement_from_date","principal_procedure_code","procedure_date_map"]].to_csv("../output/procedures array/sample_principal_procedure_info.csv")

sample_patient_info[["patient_id","claim_statement_from_date","line_level_procedure_code","previous_line_level_procedure_code_array"]].to_csv("../output/procedures array/sample_line_level_procedure_info.csv")

### EDA

In [13]:
mx_submits_eda = EDAAnalyzer(mx_submits_spark_manager)

In [15]:
mx_submits_eda.get_top_n_repeated_values("principal_procedure_code",5)

  principal_procedure_code   count
0                    99213  577772
1                    99214  480484
2                    97110  143173
3                     None  140875
4                    36415  122611